# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20180626_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
