# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
