# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_users_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
