# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='descr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
