# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_auto_20180629_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
